src/Kooboo.Commerce.Web/Areas/Kooboo.Commerce.Activities.InvoiceReminder/Controllers/InvoiceReminderController.cs
using Kooboo.CMS.Common;
using Kooboo.CMS.Common.Runtime.Dependency;
using Kooboo.Commerce.Data;
using Kooboo.Commerce.Web.Mvc;
using Kooboo.Commerce.Web.Mvc.Controllers;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kooboo.Commerce.Activities.InvoiceReminder.Controllers
{
    public class InvoiceReminderController : CommerceControllerBase
    {
        private IRepository<ActivityRule> _ruleRepository;

        public InvoiceReminderController(IRepository<ActivityRule> ruleRepository)
        {
            _ruleRepository = ruleRepository;
        }

        public ActionResult GetConfig(int ruleId, int attachedActivityInfoId)
        {
            var rule = _ruleRepository.Get(ruleId);
            var attachedActivity = rule.AttachedActivityInfos.Find(attachedActivityInfoId);
            var config = attachedActivity.GetActivityConfig<InvoiceReminderActivityConfig>();
            return JsonNet(config).UsingClientConvention();
        }

        [HttpPost, Transactional, HandleAjaxError]
        public void SaveConfig(int ruleId, int attachedActivityInfoId, InvoiceReminderActivityConfig config)
        {
            var rule = _ruleRepository.Get(ruleId);
            var attachedActivity = rule.AttachedActivityInfos.Find(attachedActivityInfoId);
            attachedActivity.SetActivityConfig(config);
        }
    }
}

src/Kooboo.Commerce.Web/Areas/Kooboo.Commerce.Activities.InvoiceReminder/Views/Config.cshtml
<form class="common-form" id="invoice-reminder-config-form">
    <table>
        <tbody>
            <tr>
                <th>@("Subject Template".Localize())</th>
                <td>
                    <input type="text" data-bind="value: subjectTemplate" />
                </td>
            </tr>
            <tr>
                <th>@("Body Template".Localize())</th>
                <td>
                    <textarea data-bind="value: bodyTemplate"></textarea>
                </td>
            </tr>
        </tbody>
    </table>
</form>

<script>
    $(function () {

        var editor = ActivityEditor.current();
        var model = new InvoiceReminderConfigModel();
        var ruleId = editor.model().ruleId();

        editor.on('databound', function (sender, args) {
            ko.applyBindings(model, document.getElementById('invoice-reminder-config-form'));

            var attachedActivityInfoId = editor.model().attachedActivityInfoId();
            if (attachedActivityInfoId) {
                var url = '@Url.Action("GetConfig", "InvoiceReminder", new { area = Strings.AreaName })';
                return $.get(url + '?ruleId=' + ruleId + '&attachedActivityInfoId=' + attachedActivityInfoId)
                        .then(function (data) {
                            ko.mapping.fromJS(data, {}, model);
                        });
            }
        });

        editor.on('saving', function (sender, args) {
        });

        editor.on('saved', function (sender, args) {
            var attachedActivityId = editor.model().attachedActivityInfoId();
            var url = '@Url.Action("SaveConfig", "InvoiceReminder", new { area = Strings.AreaName })';
            return kb.http.safePost(url + '?ruleId=' + ruleId + '&attachedActivityInfoId=' + attachedActivityId, ko.mapping.toJS(model));
        });

        function InvoiceReminderConfigModel() {
            
            this.subjectTemplate = ko.observable();

            this.bodyTemplate = ko.observable();
        }
    });
</script>