src/Kooboo.Commerce.Web/Areas/Commerce/Models/Products/FieldValidationRuleEditorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Kooboo.Commerce.Products;

namespace Kooboo.Commerce.Web.Areas.Commerce.Models.Products {

    public class FieldValidationRuleEditorModel {

        public FieldValidationRuleEditorModel() {
        }

        public FieldValidationRuleEditorModel(FieldValidationRule rule) {
            this.Id = rule.Id;
            this.ErrorMessage = rule.ErrorMessage;
            this.ValidatorName = rule.ValidatorName;
            this.ValidatorData = rule.ValidatorData;
        }

        public void UpdateTo(FieldValidationRule rule) {
            rule.Id = this.Id;
            rule.ErrorMessage = this.ErrorMessage;
            rule.ValidatorName = this.ValidatorName;
            rule.ValidatorData = this.ValidatorData;
        }

        public int Id { get; set; }

        public string ErrorMessage { get; set; }

        [Required]
        public string ValidatorName { get; set; }

        public string ValidatorData { get; set; }
    }
}

src/Kooboo.Commerce.Web/Areas/Commerce/Models/Products/ProductEditorModel.cs
using Kooboo.Commerce.Products;
using Kooboo.Commerce.Web.Framework.Json;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Kooboo.Commerce.Web.Areas.Commerce.Models.Products
{
    public class ProductEditorModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public IdName Brand { get; set; }

        public int ProductTypeId { get; set; }

        public IList<IdName> Categories { get; set; }

        public IList<ProductImage> Images { get; set; }

        [JsonConverter(typeof(PreserveDictionaryKeyCaseConverter))]
        public IDictionary<string, string> CustomFields { get; set; }

        public IList<ProductVariantModel> Variants { get; set; }

        public bool IsPublished { get; set; }

        public ProductEditorModel()
        {
            Categories = new List<IdName>();
            Images = new List<ProductImage>();
            Variants = new List<ProductVariantModel>();
            CustomFields = new Dictionary<string, string>();
        }
    }
}

src/Kooboo.Commerce.Web/Areas/Commerce/Controllers/ProductController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Kooboo.Commerce.Products;
using Kooboo.Commerce.Settings;
using Kooboo.Commerce.Brands;
using Kooboo.Commerce.Categories;
using Kooboo.Commerce.Web.Areas.Commerce.Models.Categories;
using Kooboo.CMS.Common;
using Kooboo.Commerce.Data;
using Kooboo.Commerce.Web.Framework.Mvc;
using Kooboo.Commerce.Web.Framework.UI.Topbar;
using Kooboo.Commerce.Web.Areas.Commerce.Topbar;
using Kooboo.Commerce.Web.Areas.Commerce.Models.TabQueries;
using Kooboo.Commerce.Web.Framework.UI.Tabs.Queries;
using Kooboo.Commerce.Web.Areas.Commerce.Tabs.Queries.Products;
using Kooboo.Commerce.Web.Areas.Commerce.Tabs.Queries.Products.Default;
using Kooboo.Commerce.Web.Framework.Mvc.ModelBinding;
using AutoMapper;
using Kooboo.Commerce.Web.Areas.Commerce.Models.Products;
using Kooboo.Commerce.Web.Areas.Commerce.Models;
using System.Collections.Generic;
using Kooboo.Globalization;

namespace Kooboo.Commerce.Web.Areas.Commerce.Controllers
{
    public class ProductController : CommerceController
    {
        private SettingService _settingService;
        private ProductService _productService;
        private ProductTypeService _productTypeService;
        private BrandService _brandService;
        private CategoryService _categoryService;

        public ProductController(
                SettingService settingService,
                ProductService productService,
                ProductTypeService productTypeService,
                BrandService brandService,
                CategoryService categoryService)
        {
            _settingService = settingService;
            _productService = productService;
            _productTypeService = productTypeService;
            _brandService = brandService;
            _categoryService = categoryService;
        }

        public ActionResult Index()
        {
            var model = this.CreateTabQueryModel("Products", new DefaultProductsQuery());
            ViewBag.ProductTypes = _productTypeService.Query().ToList();

            return View(model);
        }

        [HttpGet]
        public ActionResult Create(int productTypeId)
        {
            var productType = _productTypeService.Find(productTypeId);

            PrepareProductEditing(productType, null);

            return View("Edit");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var product = _productService.Find(id);
            var productType = product.ProductType;

            PrepareProductEditing(productType, product);

            return View("Edit");
        }

        private void PrepareProductEditing(ProductType productType, Product product)
        {
            if (product != null)
            {
                ViewBag.Product = product;
                ViewBag.ToolbarCommands = TopbarCommands.GetCommands(ControllerContext, product, CurrentInstance);
            }

            ViewBag.ProductType = productType;
            ViewBag.DefaultVariantModel = CreateDefaultVariantModel(productType);
            ViewBag.ImageTypes = _settingService.Get<GlobalSettings>().Image.Types;

            var settings = _settingService.Get<GlobalSettings>();
            if (settings != null && !String.IsNullOrEmpty(settings.Currency))
            {
                ViewBag.CurrencySymbol = CurrencyInfo.GetCurrencyInfoByISOSymbol(settings.Currency).Symbol;
            }

            this.LoadTabPlugins();
        }

        [HttpGet]
        public ActionResult Get(int? id = null, int? productTypeId = null)
        {
            Product product = null;
            if (id.HasValue)
            {
                product = _productService.Find(id.Value);
            }
            if (product == null)
            {
                product = new Product
                {
                    ProductType = _productTypeService.Find(productTypeId.Value)
                };
            }

            var model = Mapper.Map<Product, ProductEditorModel>(product);

            return JsonNet(model).UsingClientConvention();
        }

        [HttpPost]
        public ActionResult Save(ProductEditorModel model)
        {
            var product = DoSave(model);
            return JsonNet(new
            {
                Id = product.Id
            }).UsingClientConvention();
        }

        private Product DoSave(ProductEditorModel model)
        {
            Product product = null;

            if (model.Id == 0)
            {
                product = new Product
                {
                    ProductType = _productTypeService.Find(model.ProductTypeId)
                };
                UpdateProduct(product, model);
                _productService.Create(product);
            }
            else
            {
                product = _productService.Find(model.Id);
                UpdateProduct(product, model);
                _productService.Update(product);
            }

            if (model.IsPublished)
            {
                _productService.Publish(product);
            }
            else
            {
                _productService.Unpublish(product);
            }

            return product;
        }

        private void UpdateProduct(Product product, ProductEditorModel model)
        {
            product.Name = model.Name;
            product.Brand = model.Brand == null ? null : _brandService.Find(model.Brand.Id);

            product.Categories.Clear();
            foreach (var category in model.Categories)
            {
                product.Categories.Add(_categoryService.Find(category.Id));
            }

            product.SetCustomFields(model.CustomFields);
            product.SetImages(model.Images);

            foreach (var variant in product.Variants.ToList())
            {
                if (!model.Variants.Any(v => v.Id == variant.Id))
                {
                    product.Variants.Remove(variant);
                }
            }

            foreach (var variantModel in model.Variants)
            {
                ProductVariant variant;

                if (variantModel.Id > 0)
                {
                    variant = product.Variants.FirstOrDefault(v => v.Id == variantModel.Id);
                }
                else
                {
                    variant = new ProductVariant();
                    product.Variants.Add(variant);
                }

                variant.Sku = variantModel.Sku;
                variant.Price = variantModel.Price;
                variant.SetVariantFields(variantModel.VariantFields);
            }
        }

        public ProductVariantModel CreateDefaultVariantModel(ProductType productType)
        {
            var variant = new ProductVariantModel();
            foreach (var fieldDef in productType.VariantFieldDefinitions)
            {
                variant.VariantFields.Add(fieldDef.Name, null);
            }

            return variant;
        }

        [HttpGet]
        public ActionResult ValidateFieldUniqueness(int productId, string fieldName, string fieldValue, string fieldType)
        {
            // Uniqueness is useless for variant fields
            if (fieldValue.Equals("VariantField", StringComparison.OrdinalIgnoreCase))
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }

            var query = _productService.Query()
                                       .Where(p => p.Id != productId)
                                       .Where(p => p.CustomFields.Any(f => f.FieldName == fieldName && f.FieldValue == fieldValue));

            var valid = !query.Any();

            return Json(valid, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            try
            {
                var product = _productService.Find(id);
                _productService.Delete(product);
                return this.JsonNet(new JsonResultData()
                {
                    ReloadPage = true
                });
            }
            catch (Exception ex)
            {
                return this.JsonNet(new { status = 1, message = ex.Message });
            }
        }
        [HttpPost]
        public ActionResult Delete(ProductModel[] model)
        {
            try
            {
                foreach (var item in model)
                {
                    var product = _productService.Find(item.Id);
                    _productService.Delete(product);
                }
                return this.JsonNet(new JsonResultData()
                {
                    ReloadPage = true
                });
            }
            catch (Exception ex)
            {
                return this.JsonNet(new { status = 1, message = ex.Message });
            }
        }

        [HttpGet]
        public ActionResult GetImageTypes()
        {
            var settings = _settingService.Get<GlobalSettings>();
            var sizes = settings.Image.Types.ToList();
            return JsonNet(sizes);
        }

        [HttpGet]
        public ActionResult GetProductType(int id)
        {
            var obj = _productTypeService.Find(id);
            return JsonNet(obj);
        }

        [HttpGet]
        public ActionResult SearchBrands(string term, int page, int pageSize = 10)
        {
            var query = _brandService.Query();

            if (!String.IsNullOrWhiteSpace(term))
            {
                query = query.Where(p => p.Name.Contains(term));
            }

            var total = query.Count();
            var totalPages = (int)Math.Ceiling(total / (double)pageSize);

            var items = query.OrderBy(p => p.Name)
                             .Skip((page - 1) * pageSize)
                             .Take(pageSize)
                             .Select(p => new IdName
                             {
                                 Id = p.Id,
                                 Name = p.Name

src/Kooboo.Commerce.Web/Areas/Commerce/Controllers/ProductTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kooboo.Web.Mvc;
using Kooboo.Web.Mvc.Paging;
using Kooboo.CMS.Common.Runtime.Dependency;
using Kooboo.Commerce.Data;
using Kooboo.Commerce.Products;
using Kooboo.Commerce.Web.Areas.Commerce.Models.Products;
using Kooboo.Commerce.Web.Areas.Commerce.Models.ProductTypes;
using Kooboo.Commerce.Web.Framework.Mvc;
using AutoMapper;

namespace Kooboo.Commerce.Web.Areas.Commerce.Controllers
{
    public class ProductTypeController : CommerceController
    {
        private readonly ProductTypeService _productTypeService;
        private readonly PredefinedCustomFieldService _customFieldService;

        public ProductTypeController(ProductTypeService productTypeService, PredefinedCustomFieldService customFieldService)
        {
            _productTypeService = productTypeService;
            _customFieldService = customFieldService;
        }

        public ActionResult Index(int page = 1, int pageSize = 50)
        {
            var model = _productTypeService.Query()
                                           .Paginate(page - 1, pageSize)
                                           .Transform(type => new ProductTypeModel
                                           {
                                               Id = type.Id,
                                               Name = type.Name,
                                               SkuAlias = type.SkuAlias,
                                               IsEnabled = type.IsEnabled
                                           })
                                           .ToPagedList();
            return View(model);
        }

        [HttpPost, HandleAjaxFormError, Transactional]
        public ActionResult Enable(ProductTypeModel[] model)
        {
            foreach (var item in model)
            {
                var type = _productTypeService.Find(item.Id);
                _productTypeService.Enable(type);
            }

            return AjaxForm().ReloadPage();
        }

        [HttpPost, HandleAjaxFormError, Transactional]
        public ActionResult Disable(ProductTypeModel[] model)
        {
            foreach (var item in model)
            {
                var type = _productTypeService.Find(item.Id);
                _productTypeService.Disable(type);
            }

            return AjaxForm().ReloadPage();
        }

        [HttpPost, HandleAjaxFormError, Transactional]
        public ActionResult Delete(ProductTypeModel[] model)
        {
            foreach (var item in model)
            {
                var productType = _productTypeService.Find(item.Id);
                _productTypeService.Delete(productType);
            }

            return AjaxForm().ReloadPage();
        }

        public ActionResult Create()
        {
            var model = Mapper.Map<ProductTypeModel>(new ProductType());
            return View(model);
        }

        public ActionResult Edit(int id, string @return)
        {
            var productType = _productTypeService.Find(id);
            var model = Mapper.Map<ProductTypeModel>(productType);
            return View(model);
        }

        [HttpPost, HandleAjaxFormError, Transactional]
        public ActionResult Save(ProductTypeModel model, string @return)
        {
            ProductType productType = null;

            if (model.Id == 0)
            {
                productType = _productTypeService.Create(new CreateProductTypeRequest
                {
                    Name = model.Name,
                    SkuAlias = model.SkuAlias,
                    CustomFields = model.CustomFieldDefinitions,
                    VariantFields = model.VariantFieldDefinitions
                });
            }
            else
            {
                productType = _productTypeService.Update(new UpdateProductTypeRequest(model.Id)
                {
                    Name = model.Name,
                    SkuAlias = model.SkuAlias,
                    CustomFields = model.CustomFieldDefinitions,
                    VariantFields = model.VariantFieldDefinitions
                });
            }

            if (model.IsEnabled)
            {
                _productTypeService.Enable(productType);
            }
            else
            {
                _productTypeService.Disable(productType);
            }

            return AjaxForm().RedirectTo(@return);
        }

        public ActionResult PredefinedFields()
        {
            var fields = _customFieldService.Query()
                                            .OrderBy(f => f.Sequence)
                                            .Select(f => new
                                            {
                                                f.Id,
                                                f.Name,
                                                f.Label,
                                                f.ControlType
                                            });

            return Json(fields, JsonRequestBehavior.AllowGet);
        }
    }
}

src/Kooboo.Commerce.Web/Areas/Commerce/Views/Product/Edit.Scripts.cshtml
@using Newtonsoft.Json
@using Kooboo.Commerce.Settings
@{
    var productType = ViewBag.ProductType as ProductType;
    var imageTypes = ViewBag.ImageTypes as IEnumerable<ImageType>;
}
@Html.Partial("_ChangePriceDialog")
@Html.Partial("_BulkAddDialog")

<script>
    $(function () {
        $('#J_ProductTabs').tabs({
            beforeActivate: function (event, ui) {
                if (ui.oldPanel) {
                    var valid = true;
                    ui.oldPanel.find('form').each(function () {
                        if (!$(this).valid()) {
                            valid = false;
                        }
                    });

                    return valid;
                }
            }
        });

        var productId = @(Request.QueryString["Id"] ?? "0");
        var productTypeId = @(productType.Id);

        var AppViewModel = function () {
            var self = this;

            self.productTypeId = productTypeId;

            self.product = {};

            self.submit = function (publish) {

                if (tinyMCE) {
                    tinyMCE.triggerSave();
                    $('[data-toggle="tinymce"]').trigger('change');
                }

                var valid = true;
                $('#product-edit-main').find('form').each(function () {
                    if (!$(this).valid()) {
                        valid = false;
                    }
                });

                if (!valid) {
                    return false;
                }

                // Notify submitting
                for (var name in window.ProductEditor.tabs) {
                    var tab = window.ProductEditor.tabs[name];
                    if (tab.onSubmitting) {
                        tab.onSubmitting({ model: self });
                    }
                }

                var model = ko.mapping.toJS(self.product);
                model.isPublished = publish;

                $.ajax({
                    url: '@Url.Action("Save")',
                    type: 'POST',
                    contentType: 'application/json',
                    data: JSON.stringify(model)
                })
                .done(function () {
                    window.leaveConfirm.pass();
                    location.href = '@Html.Raw(ViewContext.RequestContext.GetRequestValue("return"))';
                })
                .fail(function (xhr) {
                    var result = JSON.parse(xhr.responseText);
                    info.show(result.message, false);
                });
            }
        }

        var viewModel = new AppViewModel();

        window.viewModel = viewModel;

        $.get('@Url.Action("Get")', { id: productId, productTypeId: productTypeId })
         .done(function (data) {
             ko.mapping.fromJS(data, {}, viewModel.product);

             // Tabs init
             forEachTab(function (tab) {
                 if (tab.init) {
                     tab.init({
                         model: viewModel
                     })
                 }
             });
 
             // Data binding
             ko.applyBindings(viewModel, document.getElementById('product-edit-main'));
             
             // Tabs onDataBound
             forEachTab(function (tab) {
                 if (tab.onDataBound) {
                     tab.onDataBound({
                         model: viewModel
                     });
                 }
             });

             kb.ui.unobtrusive.initialize(document.body);

             $('#product-edit-main form').each(function () {
                 $.validator.unobtrusive.reparse(this);
             });

         });

        function forEachTab(action) {
            for (var name in ProductEditor.tabs) {
                var tab = ProductEditor.tabs[name];
                action(tab);
            }
        }
    });

</script>

src/Kooboo.Commerce.Web/Areas/Commerce/Views/Product/Edit.cshtml
@using Kooboo.Commerce.Web.Framework.UI.Form
@{
    Layout = "~/Areas/Commerce/Views/Shared/Blank.cshtml";

    var product = (Product)ViewBag.Product;
    var productType = (ProductType)ViewBag.ProductType;
    var controls = FormControls.Controls().ToList();

    if (!String.IsNullOrEmpty(Request.QueryString["id"]))
    {
        ViewBag.Title = "Edit " + productType.Name + ": " + product.Name;
    }
    else
    {
        ViewBag.Title = "Create " + productType.Name;
    }
}
@section Panel {
    @Html.HeaderPanel().Buttons(buttons =>
    {
        buttons.Add("Save", "save").Dropdown(dropdown =>
        {
            if (product != null && product.IsPublished)
            {
                dropdown.Add("Save").WithUrl("javascript:viewModel.submit(true);");
                dropdown.Add("Save as draft").WithUrl("javascript:viewModel.submit(false);");
            }
            else
            {
                dropdown.Add("Save").WithUrl("javascript:viewModel.submit(false);");
                dropdown.Add("Save and publish").WithUrl("javascript:viewModel.submit(true);");
            }            
        });
        
        buttons.AddTopbarCommands(ViewBag.ToolbarCommands as IEnumerable<ITopbarCommand>, typeof(Product), product == null ? null : (int?)product.Id);
        buttons.AddCancelButton();
    })
}

<script>
    window.ProductEditor = {
        tabs: {}
    };
</script>

<div id="product-edit-main">
    <div class="block">
        <div id="J_ProductTabs">
            <ul>
                <li><a href="#basic">@("Basic info".Localize())</a></li>
                <li><a href="#fields">@("Fields".Localize())</a></li>
                <li><a href="#images">@("Images".Localize())</a></li>
                <li><a href="#variants">@("Variants".Localize())</a></li>
                @Html.Partial("_TabPluginHeaders")
            </ul>
            <div id="basic">
                <form>
                    @Html.Partial("_TabBasicInfo")
                </form>
            </div>
            <div id="fields">
                <form>
                    @Html.Partial("_TabCustomFields")
                </form>
            </div>
            <div id="images">
                <form>
                    @Html.Partial("_TabImages")
                </form>
            </div>
            <div id="variants">
                <form>
                    @Html.Partial("_TabVariants")
                </form>
            </div>
            @Html.Partial("_TabPluginContents")
        </div>
    </div>
</div>

@Html.Partial("_CropImageDialog")
@Html.Partial("Edit.Scripts")

src/Kooboo.Commerce.Web/Areas/Commerce/Views/Product/Index.cshtml
@using Kooboo.Commerce.Products
@{
    ViewBag.Title = "Products".Localize();
    ViewBag.EnableSearch = true;
}

@section Panel {
    @(Html.HeaderPanel().Buttons(buttons =>
    {
        buttons.Add("Create", "add").Dropdown(items =>
        {
            var productTypes = ViewBag.ProductTypes as IEnumerable<Kooboo.Commerce.Products.ProductType>;
            if (productTypes != null)
            {
                foreach (var pt in productTypes)
                {
                    items.Add(pt.Name).WithUrl(Url.Action("Create", RouteValues.From(Request.QueryString).Merge("productTypeId", pt.Id).Merge("return", Request.RawUrl)));
                }
            }

            if (productTypes != null && productTypes.Any())
            {
                items.Add("").AsSeparator();
            }
            
            items.Add("Create product type").WithUrl(Url.Action("Create", "ProductType", RouteValues.From(Request.QueryString).Merge("return", Request.RawUrl)));
        });

        buttons.AddDeleteButton();
        buttons.AddTopbarCommands(TopbarCommands.GetCommands(ViewContext.Controller.ControllerContext), typeof(Product));
    }))
}

@Html.Partial("_TabQuery")

src/Kooboo.Commerce.Web/Areas/Commerce/Views/Product/_BulkAddDialog.cshtml
@using Newtonsoft.Json
@{
    var productType = ViewBag.ProductType as ProductType;
}

<div id="bulk-add-variant-dialog" style="display:none">
    <div class="topbar">
        <h1 class="title">@("Bulk Add".Localize())</h1>
    </div>
    <div class="wrap">
        <form class="common-form">
            <table data-bind="foreach: fields">
                <tr>
                    <th>
                        <span data-bind="text: name"></span>
                    </th>
                    <td>
                        <input type="text"
                               class="always-validate"
                               data-bind="tagbox: values, attr: { name: 'BulkVariantFieldValues_' + $index() }"
                               data-val="true"
                               data-val-required="@("Required".Localize())" />
                        <em class="tip">
                            @("Enter any number of values separated by a tab".Localize())
                        </em>
                        <div>
                            <span data-bind="attr: { 'data-valmsg-for': 'BulkVariantFieldValues_' + $index() }" data-valmsg-replace="true"></span>
                        </div>
                    </td>
                </tr>
            </table>
        </form>
        <div class="buttons">
            <a href="#" class="button gray right" data-action="cancel">@("Cancel".Localize())</a>
            <a href="#" class="button right" data-action="save">@("Save".Localize())</a>
        </div>
    </div>
</div>

<script>
    (function ($) {

        var Metadata = {
            variantFieldNames: @Html.Raw(JsonConvert.SerializeObject(productType.VariantFieldDefinitions.Select(f => f.Name)))
        };

        window.BulkAddDialog = function () {

            var self = this;
            var $dialog = null;

            self.onSave = function () { };

            self.model = {
                fields: ko.observableArray()
            };

            self.init = function () {
                $dialog = $('#bulk-add-variant-dialog').dialog({
                    modal: true,
                    autoOpen: false
                });

                $dialog.find('[data-action="save"]').click(self.save);
                $dialog.find('[data-action="cancel"]').click(self.close);

                ko.applyBindings(self.model, $dialog[0]);
            }

            self.open = function () {
                self.model.fields.removeAll();

                $.each(Metadata.variantFieldNames, function () {
                    self.model.fields.push({
                        name: this.toString(),
                        values: ko.observable()
                    });
                });

                $.validator.unobtrusive.reparse($dialog.find('form'));

                $dialog.dialog('open');
            }

            self.validate = function () {
                return $dialog.find('form').valid();
            }

            self.save = function () {
                if (!self.validate()) {
                    return false;
                }

                self.onSave.apply(self, [ko.toJS(self.model.fields)]);
                self.close();
            }

            self.close = function () {
                $dialog.dialog('close');
            }
        }

        var instance = new BulkAddDialog();
        instance.init();

        BulkAddDialog.instance = function () {
            return instance;
        };

    })(jQuery);
</script>

src/Kooboo.Commerce.Web/Areas/Commerce/Views/Product/_ChangePriceDialog.cshtml
<div id="change-price-dialog" style="display:none">
    <div class="topbar">
        <h1 class="title">@("Change Price".Localize())</h1>
    </div>
    <div class="wrap">
        <div class="common-form">
            <form>
                <table>
                    <tr>
                        <th><label>@("New price:".Localize())</label></th>
                        <td>
                            <input type="text" name="NewPrice"
                                   data-val="true"
                                   data-val-required="@("Required".Localize())"
                                   data-val-number="@("Please enter a number")" />
                            <span data-valmsg-for="NewPrice" data-valmsg-replace="true"></span>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
    </div>
    <div class="buttons">
        <a href="#" class="button gray right" data-action="cancel">@("Cancel".Localize())</a>
        <a href="#" class="button right" data-action="save">@("Save".Localize())</a>
    </div>
</div>

<script>
    (function ($) {

        window.ChangePriceDialog = function () {

            var self = this;
            var $dialog = null;

            self.onSave = function (newPrice) { };

            self.init = function () {
                $dialog = $('#change-price-dialog').dialog({
                    modal: true,
                    autoOpen: false
                });

                $.validator.unobtrusive.reparse($dialog.find('form'));

                $dialog.find('[data-action="save"]').click(self.save);
                $dialog.find('[data-action="cancel"]').click(self.close);
            }

            self.newPrice = function (value) {
                var $input = $dialog.find(':input[name="NewPrice"]');

                if (arguments.length === 0) {
                    return $input.val();
                }

                $input.val(value);
            }

            self.open = function () {
                self.newPrice(null);
                $dialog.dialog('open');
            }

            self.validate = function () {
                return $dialog.find('form').valid();
            }

            self.save = function () {
                if (!self.validate()) {
                    return false;
                }

                self.onSave(self.newPrice());
                self.close();
            }

            self.close = function () {
                $dialog.dialog('close');
            }
        }

        var instacne = new ChangePriceDialog();
        instacne.init();

        window.ChangePriceDialog.instance = function () {
            return instacne;
        };

    })(jQuery);
</script>